#!/bin/bash
#jupyter serverextension enable --sys-prefix --py scriptedforms
#echo "c.NotebookApp.default_url = '/scriptedforms/use/openlearn-example.md'" >> /srv/venv/etc/jupyter/jupyter_notebook_config.py
